name: Deploy build-aggregator
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 5"
jobs:
  deploy-build-aggregator:
    runs-on: ubuntu-latest
    container:
      image: node:18
      options: -t
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run build-aggregator
        env:
          DB_USER: admin
          DB_NAME: buildbot
          DB_BUILDS_COLLECTION_NAME: builds
          DB_CONN_STRING: "mongodb+srv://admin:${{ secrets.DB_PASSWORD }}@buildbot.ytjttwr.mongodb.net"
          RIOT_TOKEN: ${{ secrets.RIOT_TOKEN }}
        run: |
          npm ci
          npm run build-aggregator
